/*
 * Simplex3dConsole
 * Copyright (C) 2011, Aleksey Nikiforov
 *
 * This file is part of Simplex3dConsole.
 *
 * Simplex3dConsole is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Simplex3dConsole is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package simplex3d.console;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;


/**
 * @author Aleksey Nikiforov (lex)
 */
public class Splash extends JFrame implements ActionListener {

    private Timer timer;
    private int delay = 1000;
    private String feedbackText;
    private int dotCount = 0;


    /** Creates new form Splash */
    public Splash() {
        initComponents();

        timer = new Timer(delay, this);
        timer.setInitialDelay(delay);
        timer.start();
    }


    public void actionPerformed(ActionEvent e) {
        updateFeedbackLabel();
    }

    private String getDots() {
        dotCount += 1;
        if (dotCount > 3) dotCount = 1;

        String res = "";
        for (int i = 0; i < dotCount; i++) {
            res += ".";
        }

        return res;
    }

    private void updateFeedbackLabel() {
        feedbackLabel.setText("Starting Console: " + feedbackText + getDots());
    }

    public void setStatusText(final String text) {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    feedbackText = text;
                    dotCount = 0;
                    updateFeedbackLabel();
                }
            });
        } catch (Exception ignore) {}
    }

    private ImageIcon loadSplash() {
        String path = "simplex3d/console/simplex3d-logo.png";
        InputStream in = this.getClass().getClassLoader().getResourceAsStream(path);

        try {
            byte[] buff = new byte[1024];
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            int len = 0; while (len >= 0) {
                len = in.read(buff);
                if (len > 0) out.write(buff, 0, len);
            }
            in.close();

            return new ImageIcon(out.toByteArray());
        }
        catch (Exception ignore) {
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel("", loadSplash(), JLabel.CENTER);
        feedbackLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Starting Console");
        setResizable(false);
        setUndecorated(true);

        logoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logoLabel.setBorder(null);

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        feedbackLabel.setText("Starting Console: rebuilding jars...");
        feedbackLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(feedbackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static Splash showSplash() {
        final Splash[] splashRef = new Splash[1];
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    splashRef[0] = new Splash();
                    ConsoleFrame.positionMiddle(splashRef[0]);
                    splashRef[0].setVisible(true);
                }
            });
        } catch (Exception ignore) {}
        return splashRef[0];
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    // End of variables declaration//GEN-END:variables

}
