/*
 * Simplex3d, BaseMath module
 * Copyright (C) 2009-2010 Simplex3d Team
 *
 * This file is part of Simplex3dMath.
 *
 * Simplex3dMath is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Simplex3dMath is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package simplex3d.math


/** <code>Sizzle4Read</code> contains abstract read-only swizzling
 * for 4-dimensional vectors.
 *
 * @author Aleksey Nikiforov (lex)
 */
private[math] abstract class Swizzle4Read[T] extends Swizzle3Read[T] {

    def w: T


    def xw: R2 = make2(x, w)
    def yw: R2 = make2(y, w)
    def zw: R2 = make2(z, w)
    def wx: R2 = make2(w, x)
    def wy: R2 = make2(w, y)
    def wz: R2 = make2(w, z)
    def ww: R2 = make2(w, w)

    def xxw: R3 = make3(x, x, w)
    def xyw: R3 = make3(x, y, w)
    def xzw: R3 = make3(x, z, w)
    def xwx: R3 = make3(x, w, x)
    def xwy: R3 = make3(x, w, y)
    def xwz: R3 = make3(x, w, z)
    def xww: R3 = make3(x, w, w)
    def yxw: R3 = make3(y, x, w)
    def yyw: R3 = make3(y, y, w)
    def yzw: R3 = make3(y, z, w)
    def ywx: R3 = make3(y, w, x)
    def ywy: R3 = make3(y, w, y)
    def ywz: R3 = make3(y, w, z)
    def yww: R3 = make3(y, w, w)
    def zxw: R3 = make3(z, x, w)
    def zyw: R3 = make3(z, y, w)
    def zzw: R3 = make3(z, z, w)
    def zwx: R3 = make3(z, w, x)
    def zwy: R3 = make3(z, w, y)
    def zwz: R3 = make3(z, w, z)
    def zww: R3 = make3(z, w, w)
    def wxx: R3 = make3(w, x, x)
    def wxy: R3 = make3(w, x, y)
    def wxz: R3 = make3(w, x, z)
    def wxw: R3 = make3(w, x, w)
    def wyx: R3 = make3(w, y, x)
    def wyy: R3 = make3(w, y, y)
    def wyz: R3 = make3(w, y, z)
    def wyw: R3 = make3(w, y, w)
    def wzx: R3 = make3(w, z, x)
    def wzy: R3 = make3(w, z, y)
    def wzz: R3 = make3(w, z, z)
    def wzw: R3 = make3(w, z, w)
    def wwx: R3 = make3(w, w, x)
    def wwy: R3 = make3(w, w, y)
    def wwz: R3 = make3(w, w, z)
    def www: R3 = make3(w, w, w)

    def xxxw: R4 = make4(x, x, x, w)
    def xxyw: R4 = make4(x, x, y, w)
    def xxzw: R4 = make4(x, x, z, w)
    def xxwx: R4 = make4(x, x, w, x)
    def xxwy: R4 = make4(x, x, w, y)
    def xxwz: R4 = make4(x, x, w, z)
    def xxww: R4 = make4(x, x, w, w)
    def xyxw: R4 = make4(x, y, x, w)
    def xyyw: R4 = make4(x, y, y, w)
    def xyzw: R4 = make4(x, y, z, w)
    def xywx: R4 = make4(x, y, w, x)
    def xywy: R4 = make4(x, y, w, y)
    def xywz: R4 = make4(x, y, w, z)
    def xyww: R4 = make4(x, y, w, w)
    def xzxw: R4 = make4(x, z, x, w)
    def xzyw: R4 = make4(x, z, y, w)
    def xzzw: R4 = make4(x, z, z, w)
    def xzwx: R4 = make4(x, z, w, x)
    def xzwy: R4 = make4(x, z, w, y)
    def xzwz: R4 = make4(x, z, w, z)
    def xzww: R4 = make4(x, z, w, w)
    def xwxx: R4 = make4(x, w, x, x)
    def xwxy: R4 = make4(x, w, x, y)
    def xwxz: R4 = make4(x, w, x, z)
    def xwxw: R4 = make4(x, w, x, w)
    def xwyx: R4 = make4(x, w, y, x)
    def xwyy: R4 = make4(x, w, y, y)
    def xwyz: R4 = make4(x, w, y, z)
    def xwyw: R4 = make4(x, w, y, w)
    def xwzx: R4 = make4(x, w, z, x)
    def xwzy: R4 = make4(x, w, z, y)
    def xwzz: R4 = make4(x, w, z, z)
    def xwzw: R4 = make4(x, w, z, w)
    def xwwx: R4 = make4(x, w, w, x)
    def xwwy: R4 = make4(x, w, w, y)
    def xwwz: R4 = make4(x, w, w, z)
    def xwww: R4 = make4(x, w, w, w)
    def yxxw: R4 = make4(y, x, x, w)
    def yxyw: R4 = make4(y, x, y, w)
    def yxzw: R4 = make4(y, x, z, w)
    def yxwx: R4 = make4(y, x, w, x)
    def yxwy: R4 = make4(y, x, w, y)
    def yxwz: R4 = make4(y, x, w, z)
    def yxww: R4 = make4(y, x, w, w)
    def yyxw: R4 = make4(y, y, x, w)
    def yyyw: R4 = make4(y, y, y, w)
    def yyzw: R4 = make4(y, y, z, w)
    def yywx: R4 = make4(y, y, w, x)
    def yywy: R4 = make4(y, y, w, y)
    def yywz: R4 = make4(y, y, w, z)
    def yyww: R4 = make4(y, y, w, w)
    def yzxw: R4 = make4(y, z, x, w)
    def yzyw: R4 = make4(y, z, y, w)
    def yzzw: R4 = make4(y, z, z, w)
    def yzwx: R4 = make4(y, z, w, x)
    def yzwy: R4 = make4(y, z, w, y)
    def yzwz: R4 = make4(y, z, w, z)
    def yzww: R4 = make4(y, z, w, w)
    def ywxx: R4 = make4(y, w, x, x)
    def ywxy: R4 = make4(y, w, x, y)
    def ywxz: R4 = make4(y, w, x, z)
    def ywxw: R4 = make4(y, w, x, w)
    def ywyx: R4 = make4(y, w, y, x)
    def ywyy: R4 = make4(y, w, y, y)
    def ywyz: R4 = make4(y, w, y, z)
    def ywyw: R4 = make4(y, w, y, w)
    def ywzx: R4 = make4(y, w, z, x)
    def ywzy: R4 = make4(y, w, z, y)
    def ywzz: R4 = make4(y, w, z, z)
    def ywzw: R4 = make4(y, w, z, w)
    def ywwx: R4 = make4(y, w, w, x)
    def ywwy: R4 = make4(y, w, w, y)
    def ywwz: R4 = make4(y, w, w, z)
    def ywww: R4 = make4(y, w, w, w)
    def zxxw: R4 = make4(z, x, x, w)
    def zxyw: R4 = make4(z, x, y, w)
    def zxzw: R4 = make4(z, x, z, w)
    def zxwx: R4 = make4(z, x, w, x)
    def zxwy: R4 = make4(z, x, w, y)
    def zxwz: R4 = make4(z, x, w, z)
    def zxww: R4 = make4(z, x, w, w)
    def zyxw: R4 = make4(z, y, x, w)
    def zyyw: R4 = make4(z, y, y, w)
    def zyzw: R4 = make4(z, y, z, w)
    def zywx: R4 = make4(z, y, w, x)
    def zywy: R4 = make4(z, y, w, y)
    def zywz: R4 = make4(z, y, w, z)
    def zyww: R4 = make4(z, y, w, w)
    def zzxw: R4 = make4(z, z, x, w)
    def zzyw: R4 = make4(z, z, y, w)
    def zzzw: R4 = make4(z, z, z, w)
    def zzwx: R4 = make4(z, z, w, x)
    def zzwy: R4 = make4(z, z, w, y)
    def zzwz: R4 = make4(z, z, w, z)
    def zzww: R4 = make4(z, z, w, w)
    def zwxx: R4 = make4(z, w, x, x)
    def zwxy: R4 = make4(z, w, x, y)
    def zwxz: R4 = make4(z, w, x, z)
    def zwxw: R4 = make4(z, w, x, w)
    def zwyx: R4 = make4(z, w, y, x)
    def zwyy: R4 = make4(z, w, y, y)
    def zwyz: R4 = make4(z, w, y, z)
    def zwyw: R4 = make4(z, w, y, w)
    def zwzx: R4 = make4(z, w, z, x)
    def zwzy: R4 = make4(z, w, z, y)
    def zwzz: R4 = make4(z, w, z, z)
    def zwzw: R4 = make4(z, w, z, w)
    def zwwx: R4 = make4(z, w, w, x)
    def zwwy: R4 = make4(z, w, w, y)
    def zwwz: R4 = make4(z, w, w, z)
    def zwww: R4 = make4(z, w, w, w)
    def wxxx: R4 = make4(w, x, x, x)
    def wxxy: R4 = make4(w, x, x, y)
    def wxxz: R4 = make4(w, x, x, z)
    def wxxw: R4 = make4(w, x, x, w)
    def wxyx: R4 = make4(w, x, y, x)
    def wxyy: R4 = make4(w, x, y, y)
    def wxyz: R4 = make4(w, x, y, z)
    def wxyw: R4 = make4(w, x, y, w)
    def wxzx: R4 = make4(w, x, z, x)
    def wxzy: R4 = make4(w, x, z, y)
    def wxzz: R4 = make4(w, x, z, z)
    def wxzw: R4 = make4(w, x, z, w)
    def wxwx: R4 = make4(w, x, w, x)
    def wxwy: R4 = make4(w, x, w, y)
    def wxwz: R4 = make4(w, x, w, z)
    def wxww: R4 = make4(w, x, w, w)
    def wyxx: R4 = make4(w, y, x, x)
    def wyxy: R4 = make4(w, y, x, y)
    def wyxz: R4 = make4(w, y, x, z)
    def wyxw: R4 = make4(w, y, x, w)
    def wyyx: R4 = make4(w, y, y, x)
    def wyyy: R4 = make4(w, y, y, y)
    def wyyz: R4 = make4(w, y, y, z)
    def wyyw: R4 = make4(w, y, y, w)
    def wyzx: R4 = make4(w, y, z, x)
    def wyzy: R4 = make4(w, y, z, y)
    def wyzz: R4 = make4(w, y, z, z)
    def wyzw: R4 = make4(w, y, z, w)
    def wywx: R4 = make4(w, y, w, x)
    def wywy: R4 = make4(w, y, w, y)
    def wywz: R4 = make4(w, y, w, z)
    def wyww: R4 = make4(w, y, w, w)
    def wzxx: R4 = make4(w, z, x, x)
    def wzxy: R4 = make4(w, z, x, y)
    def wzxz: R4 = make4(w, z, x, z)
    def wzxw: R4 = make4(w, z, x, w)
    def wzyx: R4 = make4(w, z, y, x)
    def wzyy: R4 = make4(w, z, y, y)
    def wzyz: R4 = make4(w, z, y, z)
    def wzyw: R4 = make4(w, z, y, w)
    def wzzx: R4 = make4(w, z, z, x)
    def wzzy: R4 = make4(w, z, z, y)
    def wzzz: R4 = make4(w, z, z, z)
    def wzzw: R4 = make4(w, z, z, w)
    def wzwx: R4 = make4(w, z, w, x)
    def wzwy: R4 = make4(w, z, w, y)
    def wzwz: R4 = make4(w, z, w, z)
    def wzww: R4 = make4(w, z, w, w)
    def wwxx: R4 = make4(w, w, x, x)
    def wwxy: R4 = make4(w, w, x, y)
    def wwxz: R4 = make4(w, w, x, z)
    def wwxw: R4 = make4(w, w, x, w)
    def wwyx: R4 = make4(w, w, y, x)
    def wwyy: R4 = make4(w, w, y, y)
    def wwyz: R4 = make4(w, w, y, z)
    def wwyw: R4 = make4(w, w, y, w)
    def wwzx: R4 = make4(w, w, z, x)
    def wwzy: R4 = make4(w, w, z, y)
    def wwzz: R4 = make4(w, w, z, z)
    def wwzw: R4 = make4(w, w, z, w)
    def wwwx: R4 = make4(w, w, w, x)
    def wwwy: R4 = make4(w, w, w, y)
    def wwwz: R4 = make4(w, w, w, z)
    def wwww: R4 = make4(w, w, w, w)

    def ra = xw
    def ga = yw
    def ba = zw
    def ar = wx
    def ag = wy
    def ab = wz
    def aa = ww

    def rra = xxw
    def rga = xyw
    def rba = xzw
    def rar = xwx
    def rag = xwy
    def rab = xwz
    def raa = xww
    def gra = yxw
    def gga = yyw
    def gba = yzw
    def gar = ywx
    def gag = ywy
    def gab = ywz
    def gaa = yww
    def bra = zxw
    def bga = zyw
    def bba = zzw
    def bar = zwx
    def bag = zwy
    def bab = zwz
    def baa = zww
    def arr = wxx
    def arg = wxy
    def arb = wxz
    def ara = wxw
    def agr = wyx
    def agg = wyy
    def agb = wyz
    def aga = wyw
    def abr = wzx
    def abg = wzy
    def abb = wzz
    def aba = wzw
    def aar = wwx
    def aag = wwy
    def aab = wwz
    def aaa = www

    def rrra = xxxw
    def rrga = xxyw
    def rrba = xxzw
    def rrar = xxwx
    def rrag = xxwy
    def rrab = xxwz
    def rraa = xxww
    def rgra = xyxw
    def rgga = xyyw
    def rgba = xyzw
    def rgar = xywx
    def rgag = xywy
    def rgab = xywz
    def rgaa = xyww
    def rbra = xzxw
    def rbga = xzyw
    def rbba = xzzw
    def rbar = xzwx
    def rbag = xzwy
    def rbab = xzwz
    def rbaa = xzww
    def rarr = xwxx
    def rarg = xwxy
    def rarb = xwxz
    def rara = xwxw
    def ragr = xwyx
    def ragg = xwyy
    def ragb = xwyz
    def raga = xwyw
    def rabr = xwzx
    def rabg = xwzy
    def rabb = xwzz
    def raba = xwzw
    def raar = xwwx
    def raag = xwwy
    def raab = xwwz
    def raaa = xwww
    def grra = yxxw
    def grga = yxyw
    def grba = yxzw
    def grar = yxwx
    def grag = yxwy
    def grab = yxwz
    def graa = yxww
    def ggra = yyxw
    def ggga = yyyw
    def ggba = yyzw
    def ggar = yywx
    def ggag = yywy
    def ggab = yywz
    def ggaa = yyww
    def gbra = yzxw
    def gbga = yzyw
    def gbba = yzzw
    def gbar = yzwx
    def gbag = yzwy
    def gbab = yzwz
    def gbaa = yzww
    def garr = ywxx
    def garg = ywxy
    def garb = ywxz
    def gara = ywxw
    def gagr = ywyx
    def gagg = ywyy
    def gagb = ywyz
    def gaga = ywyw
    def gabr = ywzx
    def gabg = ywzy
    def gabb = ywzz
    def gaba = ywzw
    def gaar = ywwx
    def gaag = ywwy
    def gaab = ywwz
    def gaaa = ywww
    def brra = zxxw
    def brga = zxyw
    def brba = zxzw
    def brar = zxwx
    def brag = zxwy
    def brab = zxwz
    def braa = zxww
    def bgra = zyxw
    def bgga = zyyw
    def bgba = zyzw
    def bgar = zywx
    def bgag = zywy
    def bgab = zywz
    def bgaa = zyww
    def bbra = zzxw
    def bbga = zzyw
    def bbba = zzzw
    def bbar = zzwx
    def bbag = zzwy
    def bbab = zzwz
    def bbaa = zzww
    def barr = zwxx
    def barg = zwxy
    def barb = zwxz
    def bara = zwxw
    def bagr = zwyx
    def bagg = zwyy
    def bagb = zwyz
    def baga = zwyw
    def babr = zwzx
    def babg = zwzy
    def babb = zwzz
    def baba = zwzw
    def baar = zwwx
    def baag = zwwy
    def baab = zwwz
    def baaa = zwww
    def arrr = wxxx
    def arrg = wxxy
    def arrb = wxxz
    def arra = wxxw
    def argr = wxyx
    def argg = wxyy
    def argb = wxyz
    def arga = wxyw
    def arbr = wxzx
    def arbg = wxzy
    def arbb = wxzz
    def arba = wxzw
    def arar = wxwx
    def arag = wxwy
    def arab = wxwz
    def araa = wxww
    def agrr = wyxx
    def agrg = wyxy
    def agrb = wyxz
    def agra = wyxw
    def aggr = wyyx
    def aggg = wyyy
    def aggb = wyyz
    def agga = wyyw
    def agbr = wyzx
    def agbg = wyzy
    def agbb = wyzz
    def agba = wyzw
    def agar = wywx
    def agag = wywy
    def agab = wywz
    def agaa = wyww
    def abrr = wzxx
    def abrg = wzxy
    def abrb = wzxz
    def abra = wzxw
    def abgr = wzyx
    def abgg = wzyy
    def abgb = wzyz
    def abga = wzyw
    def abbr = wzzx
    def abbg = wzzy
    def abbb = wzzz
    def abba = wzzw
    def abar = wzwx
    def abag = wzwy
    def abab = wzwz
    def abaa = wzww
    def aarr = wwxx
    def aarg = wwxy
    def aarb = wwxz
    def aara = wwxw
    def aagr = wwyx
    def aagg = wwyy
    def aagb = wwyz
    def aaga = wwyw
    def aabr = wwzx
    def aabg = wwzy
    def aabb = wwzz
    def aaba = wwzw
    def aaar = wwwx
    def aaag = wwwy
    def aaab = wwwz
    def aaaa = wwww

    def sq = xw
    def tq = yw
    def pq = zw
    def qs = wx
    def qt = wy
    def qp = wz
    def qq = ww

    def ssq = xxw
    def stq = xyw
    def spq = xzw
    def sqs = xwx
    def sqt = xwy
    def sqp = xwz
    def sqq = xww
    def tsq = yxw
    def ttq = yyw
    def tpq = yzw
    def tqs = ywx
    def tqt = ywy
    def tqp = ywz
    def tqq = yww
    def psq = zxw
    def ptq = zyw
    def ppq = zzw
    def pqs = zwx
    def pqt = zwy
    def pqp = zwz
    def pqq = zww
    def qss = wxx
    def qst = wxy
    def qsp = wxz
    def qsq = wxw
    def qts = wyx
    def qtt = wyy
    def qtp = wyz
    def qtq = wyw
    def qps = wzx
    def qpt = wzy
    def qpp = wzz
    def qpq = wzw
    def qqs = wwx
    def qqt = wwy
    def qqp = wwz
    def qqq = www

    def sssq = xxxw
    def sstq = xxyw
    def sspq = xxzw
    def ssqs = xxwx
    def ssqt = xxwy
    def ssqp = xxwz
    def ssqq = xxww
    def stsq = xyxw
    def sttq = xyyw
    def stpq = xyzw
    def stqs = xywx
    def stqt = xywy
    def stqp = xywz
    def stqq = xyww
    def spsq = xzxw
    def sptq = xzyw
    def sppq = xzzw
    def spqs = xzwx
    def spqt = xzwy
    def spqp = xzwz
    def spqq = xzww
    def sqss = xwxx
    def sqst = xwxy
    def sqsp = xwxz
    def sqsq = xwxw
    def sqts = xwyx
    def sqtt = xwyy
    def sqtp = xwyz
    def sqtq = xwyw
    def sqps = xwzx
    def sqpt = xwzy
    def sqpp = xwzz
    def sqpq = xwzw
    def sqqs = xwwx
    def sqqt = xwwy
    def sqqp = xwwz
    def sqqq = xwww
    def tssq = yxxw
    def tstq = yxyw
    def tspq = yxzw
    def tsqs = yxwx
    def tsqt = yxwy
    def tsqp = yxwz
    def tsqq = yxww
    def ttsq = yyxw
    def tttq = yyyw
    def ttpq = yyzw
    def ttqs = yywx
    def ttqt = yywy
    def ttqp = yywz
    def ttqq = yyww
    def tpsq = yzxw
    def tptq = yzyw
    def tppq = yzzw
    def tpqs = yzwx
    def tpqt = yzwy
    def tpqp = yzwz
    def tpqq = yzww
    def tqss = ywxx
    def tqst = ywxy
    def tqsp = ywxz
    def tqsq = ywxw
    def tqts = ywyx
    def tqtt = ywyy
    def tqtp = ywyz
    def tqtq = ywyw
    def tqps = ywzx
    def tqpt = ywzy
    def tqpp = ywzz
    def tqpq = ywzw
    def tqqs = ywwx
    def tqqt = ywwy
    def tqqp = ywwz
    def tqqq = ywww
    def pssq = zxxw
    def pstq = zxyw
    def pspq = zxzw
    def psqs = zxwx
    def psqt = zxwy
    def psqp = zxwz
    def psqq = zxww
    def ptsq = zyxw
    def pttq = zyyw
    def ptpq = zyzw
    def ptqs = zywx
    def ptqt = zywy
    def ptqp = zywz
    def ptqq = zyww
    def ppsq = zzxw
    def pptq = zzyw
    def pppq = zzzw
    def ppqs = zzwx
    def ppqt = zzwy
    def ppqp = zzwz
    def ppqq = zzww
    def pqss = zwxx
    def pqst = zwxy
    def pqsp = zwxz
    def pqsq = zwxw
    def pqts = zwyx
    def pqtt = zwyy
    def pqtp = zwyz
    def pqtq = zwyw
    def pqps = zwzx
    def pqpt = zwzy
    def pqpp = zwzz
    def pqpq = zwzw
    def pqqs = zwwx
    def pqqt = zwwy
    def pqqp = zwwz
    def pqqq = zwww
    def qsss = wxxx
    def qsst = wxxy
    def qssp = wxxz
    def qssq = wxxw
    def qsts = wxyx
    def qstt = wxyy
    def qstp = wxyz
    def qstq = wxyw
    def qsps = wxzx
    def qspt = wxzy
    def qspp = wxzz
    def qspq = wxzw
    def qsqs = wxwx
    def qsqt = wxwy
    def qsqp = wxwz
    def qsqq = wxww
    def qtss = wyxx
    def qtst = wyxy
    def qtsp = wyxz
    def qtsq = wyxw
    def qtts = wyyx
    def qttt = wyyy
    def qttp = wyyz
    def qttq = wyyw
    def qtps = wyzx
    def qtpt = wyzy
    def qtpp = wyzz
    def qtpq = wyzw
    def qtqs = wywx
    def qtqt = wywy
    def qtqp = wywz
    def qtqq = wyww
    def qpss = wzxx
    def qpst = wzxy
    def qpsp = wzxz
    def qpsq = wzxw
    def qpts = wzyx
    def qptt = wzyy
    def qptp = wzyz
    def qptq = wzyw
    def qpps = wzzx
    def qppt = wzzy
    def qppp = wzzz
    def qppq = wzzw
    def qpqs = wzwx
    def qpqt = wzwy
    def qpqp = wzwz
    def qpqq = wzww
    def qqss = wwxx
    def qqst = wwxy
    def qqsp = wwxz
    def qqsq = wwxw
    def qqts = wwyx
    def qqtt = wwyy
    def qqtp = wwyz
    def qqtq = wwyw
    def qqps = wwzx
    def qqpt = wwzy
    def qqpp = wwzz
    def qqpq = wwzw
    def qqqs = wwwx
    def qqqt = wwwy
    def qqqp = wwwz
    def qqqq = wwww
}
