/*
 * Simplex3d, BaseMath module
 * Copyright (C) 2009-2010, Simplex3d Team
 *
 * This file is part of Simplex3dMath.
 *
 * Simplex3dMath is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Simplex3dMath is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package simplex3d.math


/** <code>Sizzle4Read</code> contains abstract read-only swizzling
 * for 4-dimensional vectors.
 *
 * @author Aleksey Nikiforov (ledx)
 */
private[math] abstract class Swizzle4Read extends Swizzle3Read {

  private[math] def dw: Double


  def xw: R2 = make2(dx, dw)
  def yw: R2 = make2(dy, dw)
  def zw: R2 = make2(dz, dw)
  def wx: R2 = make2(dw, dx)
  def wy: R2 = make2(dw, dy)
  def wz: R2 = make2(dw, dz)
  def ww: R2 = make2(dw, dw)

  def xxw: R3 = make3(dx, dx, dw)
  def xyw: R3 = make3(dx, dy, dw)
  def xzw: R3 = make3(dx, dz, dw)
  def xwx: R3 = make3(dx, dw, dx)
  def xwy: R3 = make3(dx, dw, dy)
  def xwz: R3 = make3(dx, dw, dz)
  def xww: R3 = make3(dx, dw, dw)
  def yxw: R3 = make3(dy, dx, dw)
  def yyw: R3 = make3(dy, dy, dw)
  def yzw: R3 = make3(dy, dz, dw)
  def ywx: R3 = make3(dy, dw, dx)
  def ywy: R3 = make3(dy, dw, dy)
  def ywz: R3 = make3(dy, dw, dz)
  def yww: R3 = make3(dy, dw, dw)
  def zxw: R3 = make3(dz, dx, dw)
  def zyw: R3 = make3(dz, dy, dw)
  def zzw: R3 = make3(dz, dz, dw)
  def zwx: R3 = make3(dz, dw, dx)
  def zwy: R3 = make3(dz, dw, dy)
  def zwz: R3 = make3(dz, dw, dz)
  def zww: R3 = make3(dz, dw, dw)
  def wxx: R3 = make3(dw, dx, dx)
  def wxy: R3 = make3(dw, dx, dy)
  def wxz: R3 = make3(dw, dx, dz)
  def wxw: R3 = make3(dw, dx, dw)
  def wyx: R3 = make3(dw, dy, dx)
  def wyy: R3 = make3(dw, dy, dy)
  def wyz: R3 = make3(dw, dy, dz)
  def wyw: R3 = make3(dw, dy, dw)
  def wzx: R3 = make3(dw, dz, dx)
  def wzy: R3 = make3(dw, dz, dy)
  def wzz: R3 = make3(dw, dz, dz)
  def wzw: R3 = make3(dw, dz, dw)
  def wwx: R3 = make3(dw, dw, dx)
  def wwy: R3 = make3(dw, dw, dy)
  def wwz: R3 = make3(dw, dw, dz)
  def www: R3 = make3(dw, dw, dw)

  def xxxw: R4 = make4(dx, dx, dx, dw)
  def xxyw: R4 = make4(dx, dx, dy, dw)
  def xxzw: R4 = make4(dx, dx, dz, dw)
  def xxwx: R4 = make4(dx, dx, dw, dx)
  def xxwy: R4 = make4(dx, dx, dw, dy)
  def xxwz: R4 = make4(dx, dx, dw, dz)
  def xxww: R4 = make4(dx, dx, dw, dw)
  def xyxw: R4 = make4(dx, dy, dx, dw)
  def xyyw: R4 = make4(dx, dy, dy, dw)
  def xyzw: R4 = make4(dx, dy, dz, dw)
  def xywx: R4 = make4(dx, dy, dw, dx)
  def xywy: R4 = make4(dx, dy, dw, dy)
  def xywz: R4 = make4(dx, dy, dw, dz)
  def xyww: R4 = make4(dx, dy, dw, dw)
  def xzxw: R4 = make4(dx, dz, dx, dw)
  def xzyw: R4 = make4(dx, dz, dy, dw)
  def xzzw: R4 = make4(dx, dz, dz, dw)
  def xzwx: R4 = make4(dx, dz, dw, dx)
  def xzwy: R4 = make4(dx, dz, dw, dy)
  def xzwz: R4 = make4(dx, dz, dw, dz)
  def xzww: R4 = make4(dx, dz, dw, dw)
  def xwxx: R4 = make4(dx, dw, dx, dx)
  def xwxy: R4 = make4(dx, dw, dx, dy)
  def xwxz: R4 = make4(dx, dw, dx, dz)
  def xwxw: R4 = make4(dx, dw, dx, dw)
  def xwyx: R4 = make4(dx, dw, dy, dx)
  def xwyy: R4 = make4(dx, dw, dy, dy)
  def xwyz: R4 = make4(dx, dw, dy, dz)
  def xwyw: R4 = make4(dx, dw, dy, dw)
  def xwzx: R4 = make4(dx, dw, dz, dx)
  def xwzy: R4 = make4(dx, dw, dz, dy)
  def xwzz: R4 = make4(dx, dw, dz, dz)
  def xwzw: R4 = make4(dx, dw, dz, dw)
  def xwwx: R4 = make4(dx, dw, dw, dx)
  def xwwy: R4 = make4(dx, dw, dw, dy)
  def xwwz: R4 = make4(dx, dw, dw, dz)
  def xwww: R4 = make4(dx, dw, dw, dw)
  def yxxw: R4 = make4(dy, dx, dx, dw)
  def yxyw: R4 = make4(dy, dx, dy, dw)
  def yxzw: R4 = make4(dy, dx, dz, dw)
  def yxwx: R4 = make4(dy, dx, dw, dx)
  def yxwy: R4 = make4(dy, dx, dw, dy)
  def yxwz: R4 = make4(dy, dx, dw, dz)
  def yxww: R4 = make4(dy, dx, dw, dw)
  def yyxw: R4 = make4(dy, dy, dx, dw)
  def yyyw: R4 = make4(dy, dy, dy, dw)
  def yyzw: R4 = make4(dy, dy, dz, dw)
  def yywx: R4 = make4(dy, dy, dw, dx)
  def yywy: R4 = make4(dy, dy, dw, dy)
  def yywz: R4 = make4(dy, dy, dw, dz)
  def yyww: R4 = make4(dy, dy, dw, dw)
  def yzxw: R4 = make4(dy, dz, dx, dw)
  def yzyw: R4 = make4(dy, dz, dy, dw)
  def yzzw: R4 = make4(dy, dz, dz, dw)
  def yzwx: R4 = make4(dy, dz, dw, dx)
  def yzwy: R4 = make4(dy, dz, dw, dy)
  def yzwz: R4 = make4(dy, dz, dw, dz)
  def yzww: R4 = make4(dy, dz, dw, dw)
  def ywxx: R4 = make4(dy, dw, dx, dx)
  def ywxy: R4 = make4(dy, dw, dx, dy)
  def ywxz: R4 = make4(dy, dw, dx, dz)
  def ywxw: R4 = make4(dy, dw, dx, dw)
  def ywyx: R4 = make4(dy, dw, dy, dx)
  def ywyy: R4 = make4(dy, dw, dy, dy)
  def ywyz: R4 = make4(dy, dw, dy, dz)
  def ywyw: R4 = make4(dy, dw, dy, dw)
  def ywzx: R4 = make4(dy, dw, dz, dx)
  def ywzy: R4 = make4(dy, dw, dz, dy)
  def ywzz: R4 = make4(dy, dw, dz, dz)
  def ywzw: R4 = make4(dy, dw, dz, dw)
  def ywwx: R4 = make4(dy, dw, dw, dx)
  def ywwy: R4 = make4(dy, dw, dw, dy)
  def ywwz: R4 = make4(dy, dw, dw, dz)
  def ywww: R4 = make4(dy, dw, dw, dw)
  def zxxw: R4 = make4(dz, dx, dx, dw)
  def zxyw: R4 = make4(dz, dx, dy, dw)
  def zxzw: R4 = make4(dz, dx, dz, dw)
  def zxwx: R4 = make4(dz, dx, dw, dx)
  def zxwy: R4 = make4(dz, dx, dw, dy)
  def zxwz: R4 = make4(dz, dx, dw, dz)
  def zxww: R4 = make4(dz, dx, dw, dw)
  def zyxw: R4 = make4(dz, dy, dx, dw)
  def zyyw: R4 = make4(dz, dy, dy, dw)
  def zyzw: R4 = make4(dz, dy, dz, dw)
  def zywx: R4 = make4(dz, dy, dw, dx)
  def zywy: R4 = make4(dz, dy, dw, dy)
  def zywz: R4 = make4(dz, dy, dw, dz)
  def zyww: R4 = make4(dz, dy, dw, dw)
  def zzxw: R4 = make4(dz, dz, dx, dw)
  def zzyw: R4 = make4(dz, dz, dy, dw)
  def zzzw: R4 = make4(dz, dz, dz, dw)
  def zzwx: R4 = make4(dz, dz, dw, dx)
  def zzwy: R4 = make4(dz, dz, dw, dy)
  def zzwz: R4 = make4(dz, dz, dw, dz)
  def zzww: R4 = make4(dz, dz, dw, dw)
  def zwxx: R4 = make4(dz, dw, dx, dx)
  def zwxy: R4 = make4(dz, dw, dx, dy)
  def zwxz: R4 = make4(dz, dw, dx, dz)
  def zwxw: R4 = make4(dz, dw, dx, dw)
  def zwyx: R4 = make4(dz, dw, dy, dx)
  def zwyy: R4 = make4(dz, dw, dy, dy)
  def zwyz: R4 = make4(dz, dw, dy, dz)
  def zwyw: R4 = make4(dz, dw, dy, dw)
  def zwzx: R4 = make4(dz, dw, dz, dx)
  def zwzy: R4 = make4(dz, dw, dz, dy)
  def zwzz: R4 = make4(dz, dw, dz, dz)
  def zwzw: R4 = make4(dz, dw, dz, dw)
  def zwwx: R4 = make4(dz, dw, dw, dx)
  def zwwy: R4 = make4(dz, dw, dw, dy)
  def zwwz: R4 = make4(dz, dw, dw, dz)
  def zwww: R4 = make4(dz, dw, dw, dw)
  def wxxx: R4 = make4(dw, dx, dx, dx)
  def wxxy: R4 = make4(dw, dx, dx, dy)
  def wxxz: R4 = make4(dw, dx, dx, dz)
  def wxxw: R4 = make4(dw, dx, dx, dw)
  def wxyx: R4 = make4(dw, dx, dy, dx)
  def wxyy: R4 = make4(dw, dx, dy, dy)
  def wxyz: R4 = make4(dw, dx, dy, dz)
  def wxyw: R4 = make4(dw, dx, dy, dw)
  def wxzx: R4 = make4(dw, dx, dz, dx)
  def wxzy: R4 = make4(dw, dx, dz, dy)
  def wxzz: R4 = make4(dw, dx, dz, dz)
  def wxzw: R4 = make4(dw, dx, dz, dw)
  def wxwx: R4 = make4(dw, dx, dw, dx)
  def wxwy: R4 = make4(dw, dx, dw, dy)
  def wxwz: R4 = make4(dw, dx, dw, dz)
  def wxww: R4 = make4(dw, dx, dw, dw)
  def wyxx: R4 = make4(dw, dy, dx, dx)
  def wyxy: R4 = make4(dw, dy, dx, dy)
  def wyxz: R4 = make4(dw, dy, dx, dz)
  def wyxw: R4 = make4(dw, dy, dx, dw)
  def wyyx: R4 = make4(dw, dy, dy, dx)
  def wyyy: R4 = make4(dw, dy, dy, dy)
  def wyyz: R4 = make4(dw, dy, dy, dz)
  def wyyw: R4 = make4(dw, dy, dy, dw)
  def wyzx: R4 = make4(dw, dy, dz, dx)
  def wyzy: R4 = make4(dw, dy, dz, dy)
  def wyzz: R4 = make4(dw, dy, dz, dz)
  def wyzw: R4 = make4(dw, dy, dz, dw)
  def wywx: R4 = make4(dw, dy, dw, dx)
  def wywy: R4 = make4(dw, dy, dw, dy)
  def wywz: R4 = make4(dw, dy, dw, dz)
  def wyww: R4 = make4(dw, dy, dw, dw)
  def wzxx: R4 = make4(dw, dz, dx, dx)
  def wzxy: R4 = make4(dw, dz, dx, dy)
  def wzxz: R4 = make4(dw, dz, dx, dz)
  def wzxw: R4 = make4(dw, dz, dx, dw)
  def wzyx: R4 = make4(dw, dz, dy, dx)
  def wzyy: R4 = make4(dw, dz, dy, dy)
  def wzyz: R4 = make4(dw, dz, dy, dz)
  def wzyw: R4 = make4(dw, dz, dy, dw)
  def wzzx: R4 = make4(dw, dz, dz, dx)
  def wzzy: R4 = make4(dw, dz, dz, dy)
  def wzzz: R4 = make4(dw, dz, dz, dz)
  def wzzw: R4 = make4(dw, dz, dz, dw)
  def wzwx: R4 = make4(dw, dz, dw, dx)
  def wzwy: R4 = make4(dw, dz, dw, dy)
  def wzwz: R4 = make4(dw, dz, dw, dz)
  def wzww: R4 = make4(dw, dz, dw, dw)
  def wwxx: R4 = make4(dw, dw, dx, dx)
  def wwxy: R4 = make4(dw, dw, dx, dy)
  def wwxz: R4 = make4(dw, dw, dx, dz)
  def wwxw: R4 = make4(dw, dw, dx, dw)
  def wwyx: R4 = make4(dw, dw, dy, dx)
  def wwyy: R4 = make4(dw, dw, dy, dy)
  def wwyz: R4 = make4(dw, dw, dy, dz)
  def wwyw: R4 = make4(dw, dw, dy, dw)
  def wwzx: R4 = make4(dw, dw, dz, dx)
  def wwzy: R4 = make4(dw, dw, dz, dy)
  def wwzz: R4 = make4(dw, dw, dz, dz)
  def wwzw: R4 = make4(dw, dw, dz, dw)
  def wwwx: R4 = make4(dw, dw, dw, dx)
  def wwwy: R4 = make4(dw, dw, dw, dy)
  def wwwz: R4 = make4(dw, dw, dw, dz)
  def wwww: R4 = make4(dw, dw, dw, dw)

  def ra = xw
  def ga = yw
  def ba = zw
  def ar = wx
  def ag = wy
  def ab = wz
  def aa = ww

  def rra = xxw
  def rga = xyw
  def rba = xzw
  def rar = xwx
  def rag = xwy
  def rab = xwz
  def raa = xww
  def gra = yxw
  def gga = yyw
  def gba = yzw
  def gar = ywx
  def gag = ywy
  def gab = ywz
  def gaa = yww
  def bra = zxw
  def bga = zyw
  def bba = zzw
  def bar = zwx
  def bag = zwy
  def bab = zwz
  def baa = zww
  def arr = wxx
  def arg = wxy
  def arb = wxz
  def ara = wxw
  def agr = wyx
  def agg = wyy
  def agb = wyz
  def aga = wyw
  def abr = wzx
  def abg = wzy
  def abb = wzz
  def aba = wzw
  def aar = wwx
  def aag = wwy
  def aab = wwz
  def aaa = www

  def rrra = xxxw
  def rrga = xxyw
  def rrba = xxzw
  def rrar = xxwx
  def rrag = xxwy
  def rrab = xxwz
  def rraa = xxww
  def rgra = xyxw
  def rgga = xyyw
  def rgba = xyzw
  def rgar = xywx
  def rgag = xywy
  def rgab = xywz
  def rgaa = xyww
  def rbra = xzxw
  def rbga = xzyw
  def rbba = xzzw
  def rbar = xzwx
  def rbag = xzwy
  def rbab = xzwz
  def rbaa = xzww
  def rarr = xwxx
  def rarg = xwxy
  def rarb = xwxz
  def rara = xwxw
  def ragr = xwyx
  def ragg = xwyy
  def ragb = xwyz
  def raga = xwyw
  def rabr = xwzx
  def rabg = xwzy
  def rabb = xwzz
  def raba = xwzw
  def raar = xwwx
  def raag = xwwy
  def raab = xwwz
  def raaa = xwww
  def grra = yxxw
  def grga = yxyw
  def grba = yxzw
  def grar = yxwx
  def grag = yxwy
  def grab = yxwz
  def graa = yxww
  def ggra = yyxw
  def ggga = yyyw
  def ggba = yyzw
  def ggar = yywx
  def ggag = yywy
  def ggab = yywz
  def ggaa = yyww
  def gbra = yzxw
  def gbga = yzyw
  def gbba = yzzw
  def gbar = yzwx
  def gbag = yzwy
  def gbab = yzwz
  def gbaa = yzww
  def garr = ywxx
  def garg = ywxy
  def garb = ywxz
  def gara = ywxw
  def gagr = ywyx
  def gagg = ywyy
  def gagb = ywyz
  def gaga = ywyw
  def gabr = ywzx
  def gabg = ywzy
  def gabb = ywzz
  def gaba = ywzw
  def gaar = ywwx
  def gaag = ywwy
  def gaab = ywwz
  def gaaa = ywww
  def brra = zxxw
  def brga = zxyw
  def brba = zxzw
  def brar = zxwx
  def brag = zxwy
  def brab = zxwz
  def braa = zxww
  def bgra = zyxw
  def bgga = zyyw
  def bgba = zyzw
  def bgar = zywx
  def bgag = zywy
  def bgab = zywz
  def bgaa = zyww
  def bbra = zzxw
  def bbga = zzyw
  def bbba = zzzw
  def bbar = zzwx
  def bbag = zzwy
  def bbab = zzwz
  def bbaa = zzww
  def barr = zwxx
  def barg = zwxy
  def barb = zwxz
  def bara = zwxw
  def bagr = zwyx
  def bagg = zwyy
  def bagb = zwyz
  def baga = zwyw
  def babr = zwzx
  def babg = zwzy
  def babb = zwzz
  def baba = zwzw
  def baar = zwwx
  def baag = zwwy
  def baab = zwwz
  def baaa = zwww
  def arrr = wxxx
  def arrg = wxxy
  def arrb = wxxz
  def arra = wxxw
  def argr = wxyx
  def argg = wxyy
  def argb = wxyz
  def arga = wxyw
  def arbr = wxzx
  def arbg = wxzy
  def arbb = wxzz
  def arba = wxzw
  def arar = wxwx
  def arag = wxwy
  def arab = wxwz
  def araa = wxww
  def agrr = wyxx
  def agrg = wyxy
  def agrb = wyxz
  def agra = wyxw
  def aggr = wyyx
  def aggg = wyyy
  def aggb = wyyz
  def agga = wyyw
  def agbr = wyzx
  def agbg = wyzy
  def agbb = wyzz
  def agba = wyzw
  def agar = wywx
  def agag = wywy
  def agab = wywz
  def agaa = wyww
  def abrr = wzxx
  def abrg = wzxy
  def abrb = wzxz
  def abra = wzxw
  def abgr = wzyx
  def abgg = wzyy
  def abgb = wzyz
  def abga = wzyw
  def abbr = wzzx
  def abbg = wzzy
  def abbb = wzzz
  def abba = wzzw
  def abar = wzwx
  def abag = wzwy
  def abab = wzwz
  def abaa = wzww
  def aarr = wwxx
  def aarg = wwxy
  def aarb = wwxz
  def aara = wwxw
  def aagr = wwyx
  def aagg = wwyy
  def aagb = wwyz
  def aaga = wwyw
  def aabr = wwzx
  def aabg = wwzy
  def aabb = wwzz
  def aaba = wwzw
  def aaar = wwwx
  def aaag = wwwy
  def aaab = wwwz
  def aaaa = wwww

  def sq = xw
  def tq = yw
  def pq = zw
  def qs = wx
  def qt = wy
  def qp = wz
  def qq = ww

  def ssq = xxw
  def stq = xyw
  def spq = xzw
  def sqs = xwx
  def sqt = xwy
  def sqp = xwz
  def sqq = xww
  def tsq = yxw
  def ttq = yyw
  def tpq = yzw
  def tqs = ywx
  def tqt = ywy
  def tqp = ywz
  def tqq = yww
  def psq = zxw
  def ptq = zyw
  def ppq = zzw
  def pqs = zwx
  def pqt = zwy
  def pqp = zwz
  def pqq = zww
  def qss = wxx
  def qst = wxy
  def qsp = wxz
  def qsq = wxw
  def qts = wyx
  def qtt = wyy
  def qtp = wyz
  def qtq = wyw
  def qps = wzx
  def qpt = wzy
  def qpp = wzz
  def qpq = wzw
  def qqs = wwx
  def qqt = wwy
  def qqp = wwz
  def qqq = www

  def sssq = xxxw
  def sstq = xxyw
  def sspq = xxzw
  def ssqs = xxwx
  def ssqt = xxwy
  def ssqp = xxwz
  def ssqq = xxww
  def stsq = xyxw
  def sttq = xyyw
  def stpq = xyzw
  def stqs = xywx
  def stqt = xywy
  def stqp = xywz
  def stqq = xyww
  def spsq = xzxw
  def sptq = xzyw
  def sppq = xzzw
  def spqs = xzwx
  def spqt = xzwy
  def spqp = xzwz
  def spqq = xzww
  def sqss = xwxx
  def sqst = xwxy
  def sqsp = xwxz
  def sqsq = xwxw
  def sqts = xwyx
  def sqtt = xwyy
  def sqtp = xwyz
  def sqtq = xwyw
  def sqps = xwzx
  def sqpt = xwzy
  def sqpp = xwzz
  def sqpq = xwzw
  def sqqs = xwwx
  def sqqt = xwwy
  def sqqp = xwwz
  def sqqq = xwww
  def tssq = yxxw
  def tstq = yxyw
  def tspq = yxzw
  def tsqs = yxwx
  def tsqt = yxwy
  def tsqp = yxwz
  def tsqq = yxww
  def ttsq = yyxw
  def tttq = yyyw
  def ttpq = yyzw
  def ttqs = yywx
  def ttqt = yywy
  def ttqp = yywz
  def ttqq = yyww
  def tpsq = yzxw
  def tptq = yzyw
  def tppq = yzzw
  def tpqs = yzwx
  def tpqt = yzwy
  def tpqp = yzwz
  def tpqq = yzww
  def tqss = ywxx
  def tqst = ywxy
  def tqsp = ywxz
  def tqsq = ywxw
  def tqts = ywyx
  def tqtt = ywyy
  def tqtp = ywyz
  def tqtq = ywyw
  def tqps = ywzx
  def tqpt = ywzy
  def tqpp = ywzz
  def tqpq = ywzw
  def tqqs = ywwx
  def tqqt = ywwy
  def tqqp = ywwz
  def tqqq = ywww
  def pssq = zxxw
  def pstq = zxyw
  def pspq = zxzw
  def psqs = zxwx
  def psqt = zxwy
  def psqp = zxwz
  def psqq = zxww
  def ptsq = zyxw
  def pttq = zyyw
  def ptpq = zyzw
  def ptqs = zywx
  def ptqt = zywy
  def ptqp = zywz
  def ptqq = zyww
  def ppsq = zzxw
  def pptq = zzyw
  def pppq = zzzw
  def ppqs = zzwx
  def ppqt = zzwy
  def ppqp = zzwz
  def ppqq = zzww
  def pqss = zwxx
  def pqst = zwxy
  def pqsp = zwxz
  def pqsq = zwxw
  def pqts = zwyx
  def pqtt = zwyy
  def pqtp = zwyz
  def pqtq = zwyw
  def pqps = zwzx
  def pqpt = zwzy
  def pqpp = zwzz
  def pqpq = zwzw
  def pqqs = zwwx
  def pqqt = zwwy
  def pqqp = zwwz
  def pqqq = zwww
  def qsss = wxxx
  def qsst = wxxy
  def qssp = wxxz
  def qssq = wxxw
  def qsts = wxyx
  def qstt = wxyy
  def qstp = wxyz
  def qstq = wxyw
  def qsps = wxzx
  def qspt = wxzy
  def qspp = wxzz
  def qspq = wxzw
  def qsqs = wxwx
  def qsqt = wxwy
  def qsqp = wxwz
  def qsqq = wxww
  def qtss = wyxx
  def qtst = wyxy
  def qtsp = wyxz
  def qtsq = wyxw
  def qtts = wyyx
  def qttt = wyyy
  def qttp = wyyz
  def qttq = wyyw
  def qtps = wyzx
  def qtpt = wyzy
  def qtpp = wyzz
  def qtpq = wyzw
  def qtqs = wywx
  def qtqt = wywy
  def qtqp = wywz
  def qtqq = wyww
  def qpss = wzxx
  def qpst = wzxy
  def qpsp = wzxz
  def qpsq = wzxw
  def qpts = wzyx
  def qptt = wzyy
  def qptp = wzyz
  def qptq = wzyw
  def qpps = wzzx
  def qppt = wzzy
  def qppp = wzzz
  def qppq = wzzw
  def qpqs = wzwx
  def qpqt = wzwy
  def qpqp = wzwz
  def qpqq = wzww
  def qqss = wwxx
  def qqst = wwxy
  def qqsp = wwxz
  def qqsq = wwxw
  def qqts = wwyx
  def qqtt = wwyy
  def qqtp = wwyz
  def qqtq = wwyw
  def qqps = wwzx
  def qqpt = wwzy
  def qqpp = wwzz
  def qqpq = wwzw
  def qqqs = wwwx
  def qqqt = wwwy
  def qqqp = wwwz
  def qqqq = wwww
}
